import { VocabularyItem } from "../types";

export const vocabularyList: (VocabularyItem & { level: string })[] = [
  // A1 Seviyesi (Başlangıç)
  { turkish: "Mutlu", english: "happy", definition: "Feeling, showing, or causing pleasure or satisfaction.", level: "A1" },
  { turkish: "Üzgün", english: "sad", definition: "Unhappy or sorry.", level: "A1" },
  { turkish: "Hızlı", english: "fast", definition: "Moving or happening quickly, or able to move or happen quickly.", level: "A1" },
  { turkish: "Yavaş", english: "slow", definition: "Moving, happening, or doing something without much speed.", level: "A1" },
  { turkish: "Sıcak", english: "hot", definition: "Having a high temperature.", level: "A1" },
  { turkish: "Soğuk", english: "cold", definition: "At a low temperature, especially when compared to the temperature of the human body.", level: "A1" },
  { turkish: "Su", english: "water", definition: "A clear liquid, without colour or taste, that falls from the sky as rain.", level: "A1" },
  { turkish: "Elma", english: "apple", definition: "A round fruit with firm, white flesh and a green, red, or yellow skin.", level: "A1" },
  { turkish: "Kırmızı", english: "red", definition: "Of the colour of fresh blood.", level: "A1" },
  { turkish: "Mavi", english: "blue", definition: "Of the colour of the sky without clouds on a bright day.", level: "A1" },
  { turkish: "Büyük", english: "big", definition: "Large in size or amount.", level: "A1" },
  { turkish: "Küçük", english: "small", definition: "Little in size or amount when compared with what is typical or average.", level: "A1" },
  { turkish: "Ev", english: "house", definition: "A building that people, usually one family, live in.", level: "A1" },
  { turkish: "Okul", english: "school", definition: "A place where children go to be educated.", level: "A1" },
  { turkish: "Araba", english: "car", definition: "A road vehicle with an engine, four wheels, and seats for a small number of people.", level: "A1" },
  { turkish: "Kitap", english: "book", definition: "A written text that can be published in printed or electronic form.", level: "A1" },
  { turkish: "Kalem", english: "pen", definition: "A long, thin object used for writing or drawing with ink.", level: "A1" },
  { turkish: "Masa", english: "table", definition: "A flat surface, usually supported by four legs, used for putting things on.", level: "A1" },
  { turkish: "Kapı", english: "door", definition: "A flat object that is used to close the entrance of something such as a room or building.", level: "A1" },
  { turkish: "Pencere", english: "window", definition: "A space usually filled with glass in the wall of a building or in a vehicle.", level: "A1" },
  { turkish: "Anne", english: "mother", definition: "A female parent.", level: "A1" },
  { turkish: "Baba", english: "father", definition: "A male parent.", level: "A1" },
  { turkish: "Arkadaş", english: "friend", definition: "A person who you like and enjoy being with.", level: "A1" },
  { turkish: "Gelmek", english: "come", definition: "To move or travel towards the speaker or with the speaker.", level: "A1" },
  { turkish: "Gitmek", english: "go", definition: "To travel or move to another place.", level: "A1" },
  { turkish: "Yemek", english: "eat", definition: "To put or take food into the mouth, chew it, and swallow it.", level: "A1" },
  { turkish: "İçmek", english: "drink", definition: "To take liquid into the body through the mouth.", level: "A1" },
  { turkish: "Uyumak", english: "sleep", definition: "To be in the state of rest when your eyes are closed, your body is not active.", level: "A1" },
  { turkish: "Çalışmak", english: "work", definition: "To do an activity or job that you get money for.", level: "A1" },
  { turkish: "Sevmek", english: "love", definition: "To have strong feelings of liking a friend or person in your family.", level: "A1" },
  { turkish: "Öğrenci", english: "student", definition: "A person who is learning at a college or university.", level: "A1" },
  { turkish: "Öğretmen", english: "teacher", definition: "Someone whose job is to teach in a school or college.", level: "A1" },
  { turkish: "Doktor", english: "doctor", definition: "A person with a medical degree whose job is to treat people who are ill or hurt.", level: "A1" },
  { turkish: "Para", english: "money", definition: "Coins or notes that are used to buy things.", level: "A1" },
  { turkish: "Zaman", english: "time", definition: "The indefinite continued progress of existence and events in the past, present, and future.", level: "A1" },
  { turkish: "Şehir", english: "city", definition: "A large town.", level: "A1" },
  { turkish: "Ülke", english: "country", definition: "An area of land that has its own government, army, etc.", level: "A1" },
  { turkish: "Yol", english: "road", definition: "A long, hard surface built for vehicles to travel along.", level: "A1" },
  { turkish: "Sokak", english: "street", definition: "A public road in a city or town.", level: "A1" },
  { turkish: "Oda", english: "room", definition: "A part of the inside of a building that is separated from other parts by walls.", level: "A1" },
  { turkish: "Aile", english: "family", definition: "A group of people who are related to each other, such as a mother, a father, and their children.", level: "A1" },
  { turkish: "Hayvan", english: "animal", definition: "A living thing that is not a human being or plant.", level: "A1" },
  { turkish: "Köpek", english: "dog", definition: "A common animal with four legs, especially kept by people as a pet or to hunt or guard things.", level: "A1" },
  { turkish: "Kedi", english: "cat", definition: "A small animal with fur, four legs, a tail, and claws, usually kept as a pet or for catching mice.", level: "A1" },
  { turkish: "Kuş", english: "bird", definition: "A creature with feathers and wings, usually able to fly.", level: "A1" },
  { turkish: "Güneş", english: "sun", definition: "The star that provides light and heat for the earth under which we live.", level: "A1" },
  { turkish: "Ay", english: "moon", definition: "The round object that moves in the sky around the earth and can be seen at night.", level: "A1" },
  { turkish: "Gün", english: "day", definition: "A period of 24 hours, especially from twelve o'clock one night to twelve o'clock the next night.", level: "A1" },
  { turkish: "Gece", english: "night", definition: "The part of every 24-hour period when it is dark because there is very little light from the sun.", level: "A1" },
  { turkish: "Sabah", english: "morning", definition: "The early part of the day, from the time when the people wake up until 12 o'clock in the middle of the day.", level: "A1" },

  // A2 Seviyesi (Temel)
  { turkish: "Dün", english: "yesterday", definition: "On the day before today.", level: "A2" },
  { turkish: "Yarın", english: "tomorrow", definition: "The day after today.", level: "A2" },
  { turkish: "Sıkıcı", english: "boring", definition: "Not interesting or exciting.", level: "A2" },
  { turkish: "Heyecanlı", english: "excited", definition: "Feeling very happy and enthusiastic.", level: "A2" },
  { turkish: "Pahalı", english: "expensive", definition: "Costing a lot of money.", level: "A2" },
  { turkish: "Ucuz", english: "cheap", definition: "Costing little money or less than is usual or expected.", level: "A2" },
  { turkish: "Tehlikeli", english: "dangerous", definition: "Able or likely to cause harm or death.", level: "A2" },
  { turkish: "Güvenli", english: "safe", definition: "Not in danger or likely to be harmed.", level: "A2" },
  { turkish: "Tatil", english: "holiday", definition: "A time when someone does not go to work or school but is free to do what they want.", level: "A2" },
  { turkish: "Havaalanı", english: "airport", definition: "A place where aircraft regularly take off and land.", level: "A2" },
  { turkish: "Müşteri", english: "customer", definition: "A person who buys goods or a service.", level: "A2" },
  { turkish: "Mektup", english: "letter", definition: "A written message from one person to another, usually put in an envelope.", level: "A2" },
  { turkish: "Sözlük", english: "dictionary", definition: "A book that contains a list of words in alphabetical order and explains their meanings.", level: "A2" },
  { turkish: "Ünlü", english: "famous", definition: "Known and recognized by many people.", level: "A2" },
  { turkish: "Ziyaret", english: "visit", definition: "To go to a place in order to look at it, or to a person in order to spend time with them.", level: "A2" },
  { turkish: "Davet", english: "invite", definition: "To ask or request someone to go to an event.", level: "A2" },
  { turkish: "Satmak", english: "sell", definition: "To give something to someone else in return for money.", level: "A2" },
  { turkish: "Satın Almak", english: "buy", definition: "To get something by paying money for it.", level: "A2" },
  { turkish: "Giyinmek", english: "wear", definition: "To have clothing, jewellery, etc. on your body.", level: "A2" },
  { turkish: "Unutmak", english: "forget", definition: "To be unable to remember a fact, something that happened, or how to do something.", level: "A2" },
  { turkish: "Hatırlamak", english: "remember", definition: "To be able to bring back a piece of information into your mind.", level: "A2" },
  { turkish: "İnanmak", english: "believe", definition: "To think that something is true, correct, or real.", level: "A2" },
  { turkish: "Anlamak", english: "understand", definition: "To know the meaning of something that someone says.", level: "A2" },
  { turkish: "Açıklamak", english: "explain", definition: "To make something clear or easy to understand.", level: "A2" },
  { turkish: "Meyve", english: "fruit", definition: "The soft part containing seeds that is produced by a plant.", level: "A2" },
  { turkish: "Sebze", english: "vegetable", definition: "A plant, root, seed, or pod that is used as food.", level: "A2" },
  { turkish: "Sağlık", english: "health", definition: "The condition of the body and the degree to which it is free from illness.", level: "A2" },
  { turkish: "Kütüphane", english: "library", definition: "A building, room, or organization that has a collection of books.", level: "A2" },
  { turkish: "Trafik", english: "traffic", definition: "The number of vehicles moving along roads.", level: "A2" },
  { turkish: "Hava", english: "weather", definition: "The conditions in the air above the earth such as wind, rain, or temperature.", level: "A2" },
  { turkish: "Kıyafet", english: "clothes", definition: "Things such as dresses and trousers that you wear to cover your body.", level: "A2" },
  { turkish: "Kaza", english: "accident", definition: "Something bad that happens that is not expected or intended.", level: "A2" },
  { turkish: "Macera", english: "adventure", definition: "An unusual, exciting, and possibly dangerous activity.", level: "A2" },
  { turkish: "Bisiklet", english: "bicycle", definition: "A two-wheeled vehicle that you sit on and move by turning the two pedals.", level: "A2" },
  { turkish: "Köprü", english: "bridge", definition: "A structure that is built over a river, road, or railway to allow people and vehicles to cross.", level: "A2" },
  { turkish: "Meşgul", english: "busy", definition: "If you are busy, you are working hard, or giving your attention to a particular thing.", level: "A2" },
  { turkish: "Erken", english: "early", definition: "Near the beginning of a period of time, or before the usual, expected, or planned time.", level: "A2" },
  { turkish: "Geç", english: "late", definition: "Happening or arriving after the planned, expected, usual, or necessary time.", level: "A2" },
  { turkish: "Kazanmak", english: "earn", definition: "To get money for work that you do.", level: "A2" },
  { turkish: "Harcamak", english: "spend", definition: "To give money as a payment for something.", level: "A2" },
  { turkish: "Biriktirmek/Kurtarmak", english: "save", definition: "To keep something, especially money, for use in the future.", level: "A2" },
  { turkish: "Başarısız Olmak", english: "fail", definition: "To not succeed in what you are trying to achieve or are expected to do.", level: "A2" },
  { turkish: "Geçmek", english: "pass", definition: "To be successful in an exam, course, etc.", level: "A2" },
  { turkish: "Umut Etmek", english: "hope", definition: "To want something to happen or to be true, and usually have a good reason to think that it might.", level: "A2" },
  { turkish: "Şans", english: "luck", definition: "The force that causes things, especially good things, to happen to you by chance.", level: "A2" },

  // B1 Seviyesi (Orta)
  { turkish: "Deneyim", english: "experience", definition: "Knowledge or skill from doing, seeing, or feeling things.", level: "B1" },
  { turkish: "Fırsat", english: "opportunity", definition: "An occasion or situation that makes it possible to do something.", level: "B1" },
  { turkish: "Geliştirmek", english: "develop", definition: "To grow or change into a more advanced, larger, or stronger form.", level: "B1" },
  { turkish: "Çevre", english: "environment", definition: "The air, water, and land in or on which people, animals, and plants live.", level: "B1" },
  { turkish: "Kirlilik", english: "pollution", definition: "Damage caused to water, air, etc. by harmful substances or waste.", level: "B1" },
  { turkish: "Nüfus", english: "population", definition: "All the people living in a particular country, area, or place.", level: "B1" },
  { turkish: "Geleneksel", english: "traditional", definition: "Following or belonging to the customs or ways of behaving that have continued for a long time.", level: "B1" },
  { turkish: "Gerekli", english: "necessary", definition: "Needed in order to achieve a particular result.", level: "B1" },
  { turkish: "Hemen", english: "immediately", definition: "Now or without waiting or thinking.", level: "B1" },
  { turkish: "Kesinlikle", english: "definitely", definition: "Without any doubt.", level: "B1" },
  { turkish: "Aslında", english: "actually", definition: "In fact or really.", level: "B1" },
  { turkish: "Ne yazık ki", english: "unfortunately", definition: "Used to say that something is sad, disappointing, or has a bad effect.", level: "B1" },
  { turkish: "Başarmak", english: "succeed", definition: "To achieve something that you have been aiming for.", level: "B1" },
  { turkish: "Şikayet", english: "complain", definition: "To say that something is wrong or not satisfactory.", level: "B1" },
  { turkish: "Önermek", english: "suggest", definition: "To mention an idea, possible plan, or action for other people to consider.", level: "B1" },
  { turkish: "Tahmin", english: "guess", definition: "To give an answer to a particular question when you do not have all the facts.", level: "B1" },
  { turkish: "Çözüm", english: "solution", definition: "The answer to a problem.", level: "B1" },
  { turkish: "Bilgi", english: "knowledge", definition: "Understanding of or information about a subject that you get by experience or study.", level: "B1" },
  { turkish: "Eğitim", english: "education", definition: "The process of teaching or learning, especially in a school or college.", level: "B1" },
  { turkish: "Hükümet", english: "government", definition: "The group of people who officially control a country.", level: "B1" },
  { turkish: "Başvuru", english: "application", definition: "An official request for something, usually in writing.", level: "B1" },
  { turkish: "Kariyer", english: "career", definition: "The job or series of jobs that you do during your working life.", level: "B1" },
  { turkish: "Fark", english: "difference", definition: "The way in which two or more things which you are comparing are not the same.", level: "B1" },
  { turkish: "Başarı", english: "success", definition: "The achieving of the results wanted or hoped for.", level: "B1" },
  { turkish: "Zorluk", english: "challenge", definition: "Something that needs great mental or physical effort in order to be done successfully.", level: "B1" },
  { turkish: "Bağımsız", english: "independent", definition: "Not influenced or controlled in any way by other people, events, or things.", level: "B1" },
  { turkish: "Özellik", english: "feature", definition: "A typical quality or an important part of something.", level: "B1" },
  { turkish: "İletişim", english: "communication", definition: "The act of communicating with people.", level: "B1" },
  { turkish: "Eğlence", english: "entertainment", definition: "Shows, films, television, or other performances or activities that entertain people.", level: "B1" },
  { turkish: "Hayran Olmak", english: "admire", definition: "To find someone or something attractive and pleasant to look at.", level: "B1" },
  { turkish: "Kabul Etmek", english: "admit", definition: "To agree that something is true, especially unwillingly.", level: "B1" },
  { turkish: "Tavsiye", english: "advice", definition: "An opinion that someone offers you about what you should do or how you should act in a particular situation.", level: "B1" },
  { turkish: "Gücü Yetmek", english: "afford", definition: "To be able to buy or do something because you have enough money or time.", level: "B1" },
  { turkish: "Korkmuş", english: "afraid", definition: "Feeling fear, or feeling worry about the possible results of a particular situation.", level: "B1" },
  { turkish: "Katılmak", english: "agree", definition: "To have the same opinion.", level: "B1" },
  { turkish: "İzin Vermek", english: "allow", definition: "To give permission for someone to do something, or to not prevent something from happening.", level: "B1" },
  { turkish: "Hırslı", english: "ambitious", definition: "Having a strong wish to be successful, powerful, or rich.", level: "B1" },
  { turkish: "Duyurmak", english: "announce", definition: "To make something known or tell people about something officially.", level: "B1" },

  // B2 Seviyesi (Üst Orta)
  { turkish: "Önemli", english: "significant", definition: "Important or noticeable.", level: "B2" },
  { turkish: "Sonuç", english: "consequence", definition: "A result of a particular action or situation, often one that is bad or not convenient.", level: "B2" },
  { turkish: "Müzakere", english: "negotiate", definition: "To have formal discussions with someone in order to reach an agreement.", level: "B2" },
  { turkish: "Öncelik", english: "priority", definition: "Something that is very important and must be dealt with before other things.", level: "B2" },
  { turkish: "Takdir Etmek", english: "appreciate", definition: "To recognize how good someone or something is and to value him, her, or it.", level: "B2" },
  { turkish: "Yaklaşım", english: "approach", definition: "A way of considering or doing something.", level: "B2" },
  { turkish: "Faydalı", english: "beneficial", definition: "Helpful, useful, or good.", level: "B2" },
  { turkish: "Karmaşık", english: "complex", definition: "Involving a lot of different but related parts.", level: "B2" },
  { turkish: "Kavram", english: "concept", definition: "A principle or idea.", level: "B2" },
  { turkish: "Çatışma", english: "conflict", definition: "An active disagreement between people with opposing opinions or principles.", level: "B2" },
  { turkish: "Katkıda Bulunmak", english: "contribute", definition: "To give something, especially money, in order to provide or achieve something together with other people.", level: "B2" },
  { turkish: "İkna Etmek", english: "convince", definition: "To persuade someone or make someone certain.", level: "B2" },
  { turkish: "Gösteri", english: "demonstrate", definition: "To show or make something clear.", level: "B2" },
  { turkish: "Vurgulamak", english: "emphasize", definition: "To show that something is very important or worth giving attention to.", level: "B2" },
  { turkish: "Sonuçta", english: "eventually", definition: "In the end, especially after a long time or a lot of effort.", level: "B2" },
  { turkish: "Kanıt", english: "evidence", definition: "One or more reasons for believing that something is or is not true.", level: "B2" },
  { turkish: "Garanti", english: "guarantee", definition: "A promise that something will be done or will happen.", level: "B2" },
  { turkish: "Soruşturma", english: "investigation", definition: "The act or process of examining a crime, problem, statement, etc. carefully.", level: "B2" },
  { turkish: "Potansiyel", english: "potential", definition: "Possible when the necessary conditions exist.", level: "B2" },
  { turkish: "Psikoloji", english: "psychology", definition: "The scientific study of the way the human mind works and how it influences behaviour.", level: "B2" },
  { turkish: "Yatırım", english: "investment", definition: "The act of putting money, effort, time, etc. into something to make a profit or get an advantage.", level: "B2" },
  { turkish: "İnovasyon", english: "innovation", definition: "A new idea or method.", level: "B2" },
  { turkish: "Sürdürülebilir", english: "sustainable", definition: "Able to be maintained at a certain rate or level.", level: "B2" },
  { turkish: "Alternatif", english: "alternative", definition: "An alternative plan or method is one that you can use if you do not want to use another one.", level: "B2" },
  { turkish: "Kapasite", english: "capacity", definition: "The total amount that can be contained or produced.", level: "B2" },
  { turkish: "Analiz", english: "analysis", definition: "The act of analysing something.", level: "B2" },
  { turkish: "Tahmin Etmek", english: "predict", definition: "To say that an event or action will happen in the future, especially as a result of knowledge or experience.", level: "B2" },
  { turkish: "Yansıtmak", english: "reflect", definition: "To show, express, or be a sign of something.", level: "B2" },
  { turkish: "Emmek/Kavramak", english: "absorb", definition: "To take something in, especially gradually.", level: "B2" },
  { turkish: "Suçlamak", english: "accuse", definition: "To say that someone has done something morally wrong, illegal, or unkind.", level: "B2" },
  { turkish: "Uyum Sağlamak", english: "adapt", definition: "To change, or to change something, to suit different conditions or uses.", level: "B2" },
  { turkish: "Ayarlamak", english: "adjust", definition: "To change something slightly, especially to make it more correct, effective, or suitable.", level: "B2" },
  { turkish: "Yönetim", english: "administration", definition: "The arrangements and tasks needed to control the operation of a plan or organization.", level: "B2" },
  { turkish: "Etkilemek", english: "affect", definition: "To have an influence on someone or something, or to cause a change in someone or something.", level: "B2" },
  { turkish: "Değiştirmek", english: "alter", definition: "To change something, usually slightly, or to cause the characteristics of something to change.", level: "B2" },
  { turkish: "Belirgin", english: "apparent", definition: "Able to be seen or understood.", level: "B2" },
  { turkish: "Cazibe/Başvuru", english: "appeal", definition: "A request to the public for money, information, or help.", level: "B2" },

  // C1 Seviyesi (İleri)
  { turkish: "Terk Etmek", english: "abandon", definition: "To leave a place, thing, or person, usually for ever.", level: "C1" },
  { turkish: "Biriktirmek", english: "accumulate", definition: "To collect a large number of things over a long period of time.", level: "C1" },
  { turkish: "Edinmek", english: "acquire", definition: "To get or buy something.", level: "C1" },
  { turkish: "Yeterli", english: "adequate", definition: "Enough or satisfactory for a particular purpose.", level: "C1" },
  { turkish: "Savunmak", english: "advocate", definition: "To publicly support or suggest an idea, development, or way of doing something.", level: "C1" },
  { turkish: "Tahsis Etmek", english: "allocate", definition: "To give something to someone as their share of a total amount, to use in a particular way.", level: "C1" },
  { turkish: "Belirsiz", english: "ambiguous", definition: "Having or expressing more than one possible meaning, sometimes intentionally.", level: "C1" },
  { turkish: "Değiştirmek", english: "amend", definition: "To change the words of a text, especially a law or a legal document.", level: "C1" },
  { turkish: "Ummak", english: "anticipate", definition: "To imagine or expect that something will happen.", level: "C1" },
  { turkish: "Tutarlı", english: "coherent", definition: "If an argument, set of ideas, or a plan is coherent, it is clear and carefully considered.", level: "C1" },
  { turkish: "Başlamak", english: "commence", definition: "To begin something.", level: "C1" },
  { turkish: "Kapsamlı", english: "comprehensive", definition: "Complete and including everything that is necessary.", level: "C1" },
  { turkish: "Oluşmak", english: "comprise", definition: "To have as parts or members, or to be those parts or members.", level: "C1" },
  { turkish: "Onaylamak", english: "confirm", definition: "To make an arrangement or meeting certain, often by phone or writing.", level: "C1" },
  { turkish: "Rıza", english: "consent", definition: "Permission or agreement.", level: "C1" },
  { turkish: "Önemli/Büyük", english: "considerable", definition: "Large or of noticeable importance.", level: "C1" },
  { turkish: "Kısıtlama", english: "constraint", definition: "Something that controls what you do by keeping you within particular limits.", level: "C1" },
  { turkish: "Çağdaş", english: "contemporary", definition: "Existing or happening now.", level: "C1" },
  { turkish: "Bağlam", english: "context", definition: "The situation within which something exists or happens.", level: "C1" },
  { turkish: "Tartışmalı", english: "controversial", definition: "Causing disagreement or discussion.", level: "C1" },
  { turkish: "Çok Önemli", english: "crucial", definition: "Extremely important or necessary.", level: "C1" },
  { turkish: "Para Birimi", english: "currency", definition: "The money that is used in a particular country at a particular time.", level: "C1" },
  { turkish: "İfade Etmek", english: "denote", definition: "To represent something.", level: "C1" },
  { turkish: "Tespit Etmek", english: "detect", definition: "To notice something that is partly hidden or not clear, or to discover it.", level: "C1" },
  { turkish: "Sapmak", english: "deviate", definition: "To do something that is different from the usual or common way of behaving.", level: "C1" },

  // C2 Seviyesi (Ustalık)
  { turkish: "Rağmen", english: "albeit", definition: "Although.", level: "C2" },
  { turkish: "Benzer", english: "analogous", definition: "Having similar features to another thing and therefore able to be compared with it.", level: "C2" },
  { turkish: "Keyfi", english: "arbitrary", definition: "Based on chance rather than being planned or based on reason.", level: "C2" },
  { turkish: "Elde Etmek", english: "attain", definition: "To reach or succeed in getting something.", level: "C2" },
  { turkish: "Sona Ermek", english: "cease", definition: "To stop something.", level: "C2" },
  { turkish: "Tutarlılık", english: "coherence", definition: "The situation when the parts of something fit together in a natural or reasonable way.", level: "C2" },
  { turkish: "Çakışmak", english: "coincide", definition: "To happen at or near the same time.", level: "C2" },
  { turkish: "Ticari Mal", english: "commodity", definition: "A substance or product that can be traded, bought, or sold.", level: "C2" },
  { turkish: "Eşzamanlı", english: "concurrent", definition: "Happening or existing at the same time.", level: "C2" },
  { turkish: "Sınırlandırmak", english: "confine", definition: "To limit an activity, person, or problem in some way.", level: "C2" },
  { turkish: "Ters", english: "converse", definition: "The opposite.", level: "C2" },
  { turkish: "Çarpıtmak", english: "distort", definition: "To change the shape of something so that it looks strange or unnatural.", level: "C2" },
  { turkish: "Çeşitli", english: "diverse", definition: "Including many different types of people or things.", level: "C2" },
  { turkish: "Alan", english: "domain", definition: "An area of interest or an area over which a person has control.", level: "C2" },
  { turkish: "Aşındırmak", english: "erode", definition: "To rub or be rubbed away gradually.", level: "C2" },
  { turkish: "Etik", english: "ethical", definition: "Relating to beliefs about what is morally right and wrong.", level: "C2" },
  { turkish: "Açık", english: "explicit", definition: "Clear and exact.", level: "C2" },
  { turkish: "Sonlu", english: "finite", definition: "Having a limit or end.", level: "C2" },
  { turkish: "Hiyerarşi", english: "hierarchy", definition: "A system in which people or things are arranged according to their importance.", level: "C2" },
  { turkish: "Zımni", english: "implicit", definition: "Suggested but not communicated directly.", level: "C2" },
  { turkish: "Kaçınılmaz", english: "inevitable", definition: "Certain to happen and unable to be avoided or prevented.", level: "C2" },
  { turkish: "Altyapı", english: "infrastructure", definition: "The basic systems and services, such as transport and power supplies.", level: "C2" },
  { turkish: "Doğal", english: "intrinsic", definition: "Being an extremely important and basic characteristic of a person or thing.", level: "C2" },
  { turkish: "Başlatmak", english: "invoke", definition: "To use a law in order to achieve something.", level: "C2" },
  { turkish: "Manipüle Etmek", english: "manipulate", definition: "To control something or someone to your advantage, often unfairly.", level: "C2" }
];